# получение списка студентов
#GET http://localhost:8000/api/v1/students
#Accept: application/json

# Создаинг студента
#POST http://localhost:8000/api/v1/create/
#Accept: application/json


#Детали студента
#GET http://localhost:8000/api/v1/students/2
#Accept: application/json

