#GET http://localhost:8000/api/v2/fruits/
#Accept: application/json


#GET http://localhost:8000/api/v2/fruits/1/
#Accept: application/json


#POST http://localhost:8000/api/v2/fruits/create/
#Accept: application/json
#
#{
#"title":"Банан",
#"price": 130
#}


#PUT http://localhost:8000/api/v2/fruits/update/1/
#Accept: application/json
#
#{
#"title":"Арбуз",
#"price":500
#}


#PATCH http://localhost:8000/api/v2/fruits/pr-update/1/
#Accept: application/json
#
#{
#"title":"Дастан"
#}


#DELETE http://localhost:8000/api/v2/fruits/delete/1/
#Accept: application/json