# получение списка студентов
#GET http://localhost:8000/api/v1/students
#Accept: application/json

# Создаинг студента
#POST http://localhost:8000/api/v1/create/
#Accept: application/json


#Детали студента
#GET http://localhost:8000/api/v1/students/2
#Accept: application/json


#Получение списка фруктов
#GET http://localhost:8000/api/v1/fruits
#Accept: application/json


#создание фрукта
#POST http://localhost:8000/api/v1/create_fruit/
#Accept: application/json
#
#{
#"id":5,
#"name":"banana",
#"price":130
#}


#детали фрукта
GET http://localhost:8000/api/v1/fruits/1
Accept: application/json