
#Получение списка фруктов
#GET http://localhost:8000/api/v2/fruits
#Accept: application/json


#создание фрукта
#POST http://localhost:8000/api/v2/create_fruit/
#Accept: application/json
#
#{
#"id":5,
#"name":"banana",
#"price":130
#}


#детали фрукта
GET http://localhost:8000/api/v2/fruits/1
Accept: application/json